# Compile to docker and push it to ACR

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
#- task: NuGetToolInstaller@1

#- task: NuGetCommand@2
#  inputs:
#    restoreSolution: '$(solution)'

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: JoinrpgContainerRegistry


- task: DotNetCoreCLI@2
  displayName: Build and publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/Joinrpg.Portal/Joinrpg.Portal.csproj'
    arguments: '-c Release -o $(Build.ArtifactStagingDirectory)/publish'

- task: Docker@2
  displayName: Create and push image
  inputs:
    command: buildAndPush
    buildContext: '$(Build.ArtifactStagingDirectory)/publish'
    repository: joinrpg-master
