apiVersion: v1
kind: Secret
{{- $fullName := include "portal.fullname" . }}
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}