name: Deploy to dev
on:
  workflow_dispatch:
    inputs:
      deployVersion:
        description: Docker image to deploy
        required: true

jobs:
  deploy:
    permissions: read-all
    uses: ./.github/workflows/deploy_reusable_workflow.yml
    with:
      deployVersion: ${{ github.event.inputs.deployVersion }}
      environment: dev
      environment_url: https://dev.joinrpg.ru
    secrets: inherit
